var searchData=
[
  ['testing_1',['Testing',['../building.html',1,'Building for Testing']]],
  ['tests_2',['tests',['../building.html#autotoc_md59',1,'Compiling the tests'],['../building.html#autotoc_md60',1,'Running the tests']]],
  ['that_20does_20not_20care_3',['Writing code that does not care',['../tutorial-simd.html#autotoc_md35',1,'']]],
  ['that_20is_20genuinely_20new_4',['The thing that is genuinely new',['../tutorial-quaternion.html#autotoc_md37',1,'']]],
  ['the_20algebras_5',['The algebras',['../index.html#autotoc_md26',1,'']]],
  ['the_20algebras_20themselves_6',['The algebras themselves',['../biblio.html#autotoc_md56',1,'']]],
  ['the_20construction_20and_20its_20limits_7',['The construction and its limits',['../biblio.html#autotoc_md55',1,'']]],
  ['the_20cost_20of_20each_20doubling_8',['The cost of each doubling',['../math_background.html#autotoc_md63',1,'']]],
  ['the_20dimension_9',['One call, whatever the dimension',['../index.html#autotoc_md21',1,'']]],
  ['the_20documentation_10',['Building the documentation',['../building.html#autotoc_md61',1,'']]],
  ['the_20library_20s_20response_11',['The library&apos;s response',['../math_background.html#autotoc_md68',1,'']]],
  ['the_20loss_20of_20associativity_12',['Dimension 8: the loss of associativity',['../math_background.html#autotoc_md66',1,'']]],
  ['the_20loss_20of_20commutativity_13',['Dimension 4: the loss of commutativity',['../math_background.html#autotoc_md65',1,'']]],
  ['the_20loss_20of_20division_14',['Dimension 16: the loss of division',['../math_background.html#autotoc_md67',1,'']]],
  ['the_20loss_20of_20order_15',['Dimension 2: the loss of order',['../math_background.html#autotoc_md64',1,'']]],
  ['the_20mechanism_16',['The mechanism',['../tutorial-options.html#autotoc_md50',1,'']]],
  ['the_20one_20surprise_17',['The one surprise',['../tutorial-complex.html#autotoc_md31',1,'']]],
  ['the_20tests_18',['the tests',['../building.html#autotoc_md59',1,'Compiling the tests'],['../building.html#autotoc_md60',1,'Running the tests']]],
  ['the_20thing_20that_20is_20genuinely_20new_19',['The thing that is genuinely new',['../tutorial-quaternion.html#autotoc_md37',1,'']]],
  ['them_20',['Real answers when you want them',['../index.html#autotoc_md25',1,'']]],
  ['themselves_21',['The algebras themselves',['../biblio.html#autotoc_md56',1,'']]],
  ['they_20are_22',['What they are',['../tutorial-quaternion.html#autotoc_md36',1,'']]],
  ['thing_20that_20is_20genuinely_20new_23',['The thing that is genuinely new',['../tutorial-quaternion.html#autotoc_md37',1,'']]],
  ['to_20and_20from_20other_20representations_24',['Converting to and from other representations',['../tutorial-rotation.html#autotoc_md44',1,'']]],
  ['to_20go_20from_20here_25',['Where to go from here',['../tutorial-beyond.html#autotoc_md49',1,'']]],
  ['to_20go_20next_26',['Where to go next',['../setup.html#autotoc_md77',1,'']]],
  ['to_20now_20complex_20bessel_20functions_20are_20only_20implemented_20for_20scalar_20orders_20integral_20or_20floating_27',['Up to now complex bessel functions are only implemented for scalar orders (integral or floating)',['..//__w/kyosu/kyosu/include/kyosu/details/bessel.hpp#autotoc_md0',1,'']]],
  ['to_20obtain_20poor_20precision_20with_20float_20based_20computations_28',['to obtain poor precision with float based computations.',['..//__w/kyosu/kyosu/include/kyosu/details/bessel.hpp#autotoc_md3',1,'']]],
  ['trap_3a_20from_20dimension_2016_20division_20fails_29',['Second trap: from dimension 16, division fails',['../tutorial-beyond.html#autotoc_md47',1,'']]],
  ['trap_3a_20parentheses_20are_20load_20bearing_30',['First trap: parentheses are load-bearing',['../tutorial-beyond.html#autotoc_md46',1,'']]],
  ['turns_32',['turns',['../index.html#autotoc_md24',1,'Angles in half-turns'],['../tutorial-options.html#autotoc_md52',1,'Angles in half-turns']]],
  ['two_20divisions_20instead_20of_20one_33',['Two divisions instead of one',['../tutorial-quaternion.html#autotoc_md38',1,'']]],
  ['type_34',['Naming a type',['../tutorial-complex.html#autotoc_md29',1,'']]]
];
