var searchData=
[
  ['testing_1',['Testing',['../building.html',1,'Building for Testing']]],
  ['tests_2',['tests',['../building.html#autotoc_md55',1,'Compiling the tests'],['../building.html#autotoc_md56',1,'Running the tests']]],
  ['that_20does_20not_20care_3',['Writing code that does not care',['../tutorial-simd.html#autotoc_md31',1,'']]],
  ['that_20is_20genuinely_20new_4',['The thing that is genuinely new',['../tutorial-quaternion.html#autotoc_md33',1,'']]],
  ['the_20algebras_5',['The algebras',['../index.html#autotoc_md22',1,'']]],
  ['the_20algebras_20themselves_6',['The algebras themselves',['../biblio.html#autotoc_md52',1,'']]],
  ['the_20construction_20and_20its_20limits_7',['The construction and its limits',['../biblio.html#autotoc_md51',1,'']]],
  ['the_20cost_20of_20each_20doubling_8',['The cost of each doubling',['../math_background.html#autotoc_md59',1,'']]],
  ['the_20dimension_9',['One call, whatever the dimension',['../index.html#autotoc_md17',1,'']]],
  ['the_20documentation_10',['Building the documentation',['../building.html#autotoc_md57',1,'']]],
  ['the_20library_20s_20response_11',['The library&apos;s response',['../math_background.html#autotoc_md64',1,'']]],
  ['the_20loss_20of_20associativity_12',['Dimension 8: the loss of associativity',['../math_background.html#autotoc_md62',1,'']]],
  ['the_20loss_20of_20commutativity_13',['Dimension 4: the loss of commutativity',['../math_background.html#autotoc_md61',1,'']]],
  ['the_20loss_20of_20division_14',['Dimension 16: the loss of division',['../math_background.html#autotoc_md63',1,'']]],
  ['the_20loss_20of_20order_15',['Dimension 2: the loss of order',['../math_background.html#autotoc_md60',1,'']]],
  ['the_20mechanism_16',['The mechanism',['../tutorial-options.html#autotoc_md46',1,'']]],
  ['the_20one_20surprise_17',['The one surprise',['../tutorial-complex.html#autotoc_md27',1,'']]],
  ['the_20tests_18',['the tests',['../building.html#autotoc_md55',1,'Compiling the tests'],['../building.html#autotoc_md56',1,'Running the tests']]],
  ['the_20thing_20that_20is_20genuinely_20new_19',['The thing that is genuinely new',['../tutorial-quaternion.html#autotoc_md33',1,'']]],
  ['them_20',['Real answers when you want them',['../index.html#autotoc_md21',1,'']]],
  ['themselves_21',['The algebras themselves',['../biblio.html#autotoc_md52',1,'']]],
  ['they_20are_22',['What they are',['../tutorial-quaternion.html#autotoc_md32',1,'']]],
  ['thing_20that_20is_20genuinely_20new_23',['The thing that is genuinely new',['../tutorial-quaternion.html#autotoc_md33',1,'']]],
  ['to_20and_20from_20other_20representations_24',['Converting to and from other representations',['../tutorial-rotation.html#autotoc_md40',1,'']]],
  ['to_20go_20from_20here_25',['Where to go from here',['../tutorial-beyond.html#autotoc_md45',1,'']]],
  ['to_20go_20next_26',['Where to go next',['../setup.html#autotoc_md73',1,'']]],
  ['trap_3a_20from_20dimension_2016_20division_20fails_27',['Second trap: from dimension 16, division fails',['../tutorial-beyond.html#autotoc_md43',1,'']]],
  ['trap_3a_20parentheses_20are_20load_20bearing_28',['First trap: parentheses are load-bearing',['../tutorial-beyond.html#autotoc_md42',1,'']]],
  ['turns_30',['turns',['../index.html#autotoc_md20',1,'Angles in half-turns'],['../tutorial-options.html#autotoc_md48',1,'Angles in half-turns']]],
  ['two_20divisions_20instead_20of_20one_31',['Two divisions instead of one',['../tutorial-quaternion.html#autotoc_md34',1,'']]],
  ['type_32',['Naming a type',['../tutorial-complex.html#autotoc_md25',1,'']]]
];
