var searchData=
[
  ['that_20does_20not_20care_2',['Writing code that does not care',['../tutorial-simd.html#autotoc_md31',1,'']]],
  ['that_20is_20genuinely_20new_3',['The thing that is genuinely new',['../tutorial-quaternion.html#autotoc_md33',1,'']]],
  ['the_20algebras_4',['The algebras',['../index.html#autotoc_md22',1,'']]],
  ['the_20algebras_20themselves_5',['The algebras themselves',['../biblio.html#autotoc_md52',1,'']]],
  ['the_20construction_20and_20its_20limits_6',['The construction and its limits',['../biblio.html#autotoc_md51',1,'']]],
  ['the_20cost_20of_20each_20doubling_7',['The cost of each doubling',['../math_background.html#autotoc_md55',1,'']]],
  ['the_20dimension_8',['One call, whatever the dimension',['../index.html#autotoc_md17',1,'']]],
  ['the_20library_20s_20response_9',['The library&apos;s response',['../math_background.html#autotoc_md60',1,'']]],
  ['the_20loss_20of_20associativity_10',['Dimension 8: the loss of associativity',['../math_background.html#autotoc_md58',1,'']]],
  ['the_20loss_20of_20commutativity_11',['Dimension 4: the loss of commutativity',['../math_background.html#autotoc_md57',1,'']]],
  ['the_20loss_20of_20division_12',['Dimension 16: the loss of division',['../math_background.html#autotoc_md59',1,'']]],
  ['the_20loss_20of_20order_13',['Dimension 2: the loss of order',['../math_background.html#autotoc_md56',1,'']]],
  ['the_20mechanism_14',['The mechanism',['../tutorial-options.html#autotoc_md46',1,'']]],
  ['the_20one_20surprise_15',['The one surprise',['../tutorial-complex.html#autotoc_md27',1,'']]],
  ['the_20thing_20that_20is_20genuinely_20new_16',['The thing that is genuinely new',['../tutorial-quaternion.html#autotoc_md33',1,'']]],
  ['them_17',['Real answers when you want them',['../index.html#autotoc_md21',1,'']]],
  ['themselves_18',['The algebras themselves',['../biblio.html#autotoc_md52',1,'']]],
  ['they_20are_19',['What they are',['../tutorial-quaternion.html#autotoc_md32',1,'']]],
  ['thing_20that_20is_20genuinely_20new_20',['The thing that is genuinely new',['../tutorial-quaternion.html#autotoc_md33',1,'']]],
  ['to_20and_20from_20other_20representations_21',['Converting to and from other representations',['../tutorial-rotation.html#autotoc_md40',1,'']]],
  ['to_20go_20from_20here_22',['Where to go from here',['../tutorial-beyond.html#autotoc_md45',1,'']]],
  ['to_20go_20next_23',['Where to go next',['../setup.html#autotoc_md69',1,'']]],
  ['trap_3a_20from_20dimension_2016_20division_20fails_24',['Second trap: from dimension 16, division fails',['../tutorial-beyond.html#autotoc_md43',1,'']]],
  ['trap_3a_20parentheses_20are_20load_20bearing_25',['First trap: parentheses are load-bearing',['../tutorial-beyond.html#autotoc_md42',1,'']]],
  ['turns_27',['turns',['../index.html#autotoc_md20',1,'Angles in half-turns'],['../tutorial-options.html#autotoc_md48',1,'Angles in half-turns']]],
  ['two_20divisions_20instead_20of_20one_28',['Two divisions instead of one',['../tutorial-quaternion.html#autotoc_md34',1,'']]],
  ['type_29',['Naming a type',['../tutorial-complex.html#autotoc_md25',1,'']]]
];
