var searchData=
[
  ['obtain_20poor_20precision_20with_20float_20based_20computations_0',['to obtain poor precision with float based computations.',['..//__w/kyosu/kyosu/include/kyosu/details/bessel.hpp#autotoc_md3',1,'']]],
  ['octonions_20and_20beyond_1',['Octonions and beyond',['../tutorial-beyond.html',1,'']]],
  ['of_20associativity_2',['Dimension 8: the loss of associativity',['../math_background.html#autotoc_md66',1,'']]],
  ['of_20cayley_20dickson_20algebras_3',['Mathematics of Cayley-Dickson Algebras',['../math_background.html',1,'']]],
  ['of_20commutativity_4',['Dimension 4: the loss of commutativity',['../math_background.html#autotoc_md65',1,'']]],
  ['of_20complex_20numbers_5',['A register of complex numbers',['../tutorial-simd.html#autotoc_md34',1,'']]],
  ['of_20division_6',['Dimension 16: the loss of division',['../math_background.html#autotoc_md67',1,'']]],
  ['of_20each_20doubling_7',['The cost of each doubling',['../math_background.html#autotoc_md63',1,'']]],
  ['of_20one_8',['Two divisions instead of one',['../tutorial-quaternion.html#autotoc_md38',1,'']]],
  ['of_20order_9',['Dimension 2: the loss of order',['../math_background.html#autotoc_md64',1,'']]],
  ['of_20real_20analytic_20functions_10',['Extension of real analytic functions',['../math_background.html#autotoc_md70',1,'']]],
  ['of_20reals_11',['A register of reals',['../tutorial-simd.html#autotoc_md33',1,'']]],
  ['on_20purpose_12',['What is missing on purpose',['../tutorial-complex.html#autotoc_md32',1,'']]],
  ['once_13',['Many values at once',['../tutorial-simd.html',1,'']]],
  ['one_14',['one',['../index.html#autotoc_md27',1,'Building one'],['../tutorial-quaternion.html#autotoc_md38',1,'Two divisions instead of one']]],
  ['one_20call_20scalar_20or_20simd_15',['One call, scalar or SIMD',['../index.html#autotoc_md22',1,'']]],
  ['one_20call_20whatever_20the_20dimension_16',['One call, whatever the dimension',['../index.html#autotoc_md21',1,'']]],
  ['one_20surprise_17',['The one surprise',['../tutorial-complex.html#autotoc_md31',1,'']]],
  ['one_20without_20listing_20four_20numbers_18',['Building one without listing four numbers',['../tutorial-quaternion.html#autotoc_md39',1,'']]],
  ['only_20implemented_20for_20scalar_20orders_20integral_20or_20floating_19',['Up to now complex bessel functions are only implemented for scalar orders (integral or floating)',['..//__w/kyosu/kyosu/include/kyosu/details/bessel.hpp#autotoc_md0',1,'']]],
  ['options_22',['Options',['../tutorial-options.html',1,'']]],
  ['or_20floating_23',['Up to now complex bessel functions are only implemented for scalar orders (integral or floating)',['..//__w/kyosu/kyosu/include/kyosu/details/bessel.hpp#autotoc_md0',1,'']]],
  ['or_20simd_24',['One call, scalar or SIMD',['../index.html#autotoc_md22',1,'']]],
  ['order_25',['Dimension 2: the loss of order',['../math_background.html#autotoc_md64',1,'']]],
  ['orders_20integral_20or_20floating_26',['Up to now complex bessel functions are only implemented for scalar orders (integral or floating)',['..//__w/kyosu/kyosu/include/kyosu/details/bessel.hpp#autotoc_md0',1,'']]],
  ['orientations_27',['Interpolating between orientations',['../tutorial-rotation.html#autotoc_md43',1,'']]],
  ['other_20representations_28',['Converting to and from other representations',['../tutorial-rotation.html#autotoc_md44',1,'']]]
];
