#error This file is for documentation only - DO NOT INCLUDE
/**
   \mainpage SIMD-Aware Cayley-Dickson Algebras

   <strong>KYOSU</strong> is a C++20 library for complex numbers, quaternions, octonions and the general
   \f$\mathbb{R}\f$-Cayley-Dickson algebras. It extends the usual real functions to all of them — the
   transcendentals, but also Bessel functions, Legendre polynomials and elliptic integrals — and every
   one of those functions works on a scalar and on a SIMD register alike.

   If all you need is complex numbers, that is reason enough to use it: they are the two-dimensional case,
   and they come with the same vectorization as the rest.

   ## Core Features

   ### One call, whatever the dimension
   Over two hundred functions, each taking a real or a hyper-complex argument under the same name.

   @godbolt{doc/one_call.cpp}

   ### One call, scalar or SIMD
   The same name again, on one value or on a register of them.

   @godbolt{doc/simd.cpp}

   ### Accuracy you choose
   The default keeps IEEE754 conformity at the edges of the domain; `raw` skips those checks for speed.

   @godbolt{doc/accuracy.cpp}

   ### Angles in half-turns
   With kyosu::radpi, an angle is read and returned as a multiple of \f$\pi\f$ rather than in radians.

   @godbolt{doc/half_turns.cpp}

   ### Real answers when you want them
   A real input outside a function's real domain returns a complex result, unless kyosu::real_only is
   passed, which defers to the matching EVE function and its NaN.

   @godbolt{doc/real_answers.cpp}

   ## The algebras
   Starting from IEEE `float` and `double`:
   + [**Complex numbers**](https://en.wikipedia.org/wiki/Complex_number).
   + [**Quaternions**](https://en.wikipedia.org/wiki/Quaternion).
   + [**Octonions**](https://en.wikipedia.org/wiki/Octonion).
   + [**General algebras**](https://en.wikipedia.org/wiki/Cayley%E2%80%93Dickson_construction).

   Dimensions mix freely in an operation: the result takes the largest one and the missing components
   are zero. And the algebra is the real one: past the complex numbers it stops being commutative,
   which is why kyosu::ldiv sits alongside `/`. The constants kyosu::i, kyosu::mi, kyosu::j and
   kyosu::k are there, as are kyosu::muli and kyosu::mulmi for multiplication by \f$\pm i\f$.

   @godbolt{doc/algebra.cpp}

   ### Building one
   From the parametrizations one actually reaches for — kyosu::from_euler, kyosu::from_polar,
   kyosu::from_spherical, kyosu::from_cylindrical, and axis-angle.

   @godbolt{doc/constructors.cpp}

   ## Licence

   This library is licensed under the [Boost Software License](https://opensource.org/licenses/BSL):

   ```text
   Copyright : KYOSU Project Contributors

   Boost Software License - Version 1.0 - August 17th, 2003

   Permission is hereby granted, free of charge, to any person or organization
   obtaining a copy of the software and accompanying documentation covered by
   this license (the "Software") to use, reproduce, display, distribute,
   execute, and transmit the Software, and to prepare derivative works of the
   Software, and to permit third-parties to whom the Software is furnished to
   do so, all subject to the following:

   The copyright notices in the Software and this entire statement, including
   the above license grant, this restriction and the following disclaimer,
   must be included in all copies of the Software, in whole or in part, and
   all derivative works of the Software, unless such copies or derivative
   works are solely in the form of machine-executable object code generated by
   a source language processor.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
   ```

**/