#error This file is for documentation only - DO NOT INCLUDE
/**
   \mainpage KYOSU

   # KYOSU: SIMD-Aware Cayley-Dickson Algebras
   The **KYOSU** library is a unified, high-performance C++ library for complex numbers, quaternions, octonions,
   and general $\mathbb{R}$-Cayley-Dickson algebras.

   Built natively for data-parallel execution, **KYOSU** delivers zero-cost abstraction for both scalar and vectorized math.
   It allows you to extend the domain functions you know and love into higher dimensions, keeping your computations clear
   and blazing fast.

   Even if **you just need the basics**, KYOSU remains a highly optimized, hardware-agnostic math suite for
   standard **real** and **complex** numbers operating across vector registers.

   ## Core Features
   + **Blazing Fast Data-Parallel Execution:** Seamlessly use over 200 functions in both scalar and SIMD-compatible contexts without abstraction penalties.
   + **Execution Control:** Tailor performance by choosing `raw` for maximum vectorization speed, or `pedantic` for strict IEEE754 standard conformity and lane-wise accuracy.
   + **Precision Angles:** Pass the kyosu::radpi option to calculate in exact multiples of $\pi$, completely bypassing standard floating-point representation inaccuracies within vectorized pipelines.
   + **Real-Only Fallbacks:** While out-of-bounds real inputs naturally return complex results in KYOSU (e.g., kyosu::acos(2.0)), you can enforce strictly real scalar or SIMD behavior using the kyosu::real_only flag.

   ### Supported Algebras & Types
   Starting from standard IEEE floats and doubles, KYOSU continuously scales across vector lanes:
   + [**Complex Numbers**](https://en.wikipedia.org/wiki/Complex_number).
   + [**Quaternions**](https://en.wikipedia.org/wiki/Quaternion).
   + [**Octonions**](https://en.wikipedia.org/wiki/Octonion).
   + [**General Algebras**](https://en.wikipedia.org/wiki/Cayley%E2%80%93Dickson_construction).

   Dimensionalities can be freely mixed in operations; the system automatically adopts the highest dimension and zeroes out the rest, maintaining continuous SIMD throughput without branching.

   ### Functionalities
   + **Rich Math Suite:** Supports a massive array of vectorized functions extended to hyper-complex domains,
      including Bessel functions, Legendre polynomials, elliptic integrals, and standard transcendentals.
   + **Advanced Initializers:** Construct complex geometries easily using spatial parametrizations like
      kyosu::from_euler, kyosu::from_spherical, kyosu::from_cylindrical, and axis-angle constructors.
   + **Optimized Operations:** Features full operator overloading (`+`, `-`, `*`, `/`), native left-division (kyosu::ldiv), and
      high-speed imaginary multiplication (kyosu::muli, kyosu::mulmi).
   + **Built-in Constants:** Provides instant access to foundational algebra constants like
      kyosu::i, kyosu::mi, kyosu::j, kyosu::k, and complex infinity.

   ## Kyosu Hello World

   @code
   #include <kyosu/kyosu.hpp>
   #include <iostream>

   int main()
   {

   }
   @endcode

   ## Licence

   This library is licensed under the [Boost Software License](https://opensource.org/licenses/BSL):

   ```text
   Copyright : KYOSU Project Contributors

   Boost Software License - Version 1.0 - August 17th, 2003

   Permission is hereby granted, free of charge, to any person or organization
   obtaining a copy of the software and accompanying documentation covered by
   this license (the "Software") to use, reproduce, display, distribute,
   execute, and transmit the Software, and to prepare derivative works of the
   Software, and to permit third-parties to whom the Software is furnished to
   do so, all subject to the following:

   The copyright notices in the Software and this entire statement, including
   the above license grant, this restriction and the following disclaimer,
   must be included in all copies of the Software, in whole or in part, and
   all derivative works of the Software, unless such copies or derivative
   works are solely in the form of machine-executable object code generated by
   a source language processor.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
   ```

**/