#error This file is for documentation only - DO NOT INCLUDE
/**
   \mainpage SIMD-Aware Cayley-Dickson Algebras

   <strong>KYOSU</strong> is a C++20 library for complex numbers, quaternions, octonions and the general
   \f$\mathbb{R}\f$-Cayley-Dickson algebras. It extends the usual real functions to all of them, and every
   one of those functions works on a scalar and on a SIMD register alike.

   If all you need is complex numbers, that is reason enough to use it: they are the two-dimensional case,
   and they come with the same vectorization as the rest.

   ## Core Features
   + **One call everywhere.** Over two hundred functions, each taking a scalar or a SIMD register, a real
     or a hyper-complex argument, under the same name.
   + **Accuracy you choose.** `raw` trades correctness at the edges for speed, `pedantic` keeps IEEE754
     conformity lane by lane.
   + **Angles in half-turns.** With kyosu::radpi, an angle is read and returned as a multiple of
     \f$\pi\f$ rather than in radians — kyosu::arg[kyosu::radpi] gives a half-turn as `1`.
   + **Real answers when you want them.** A real input outside a function's real domain returns a complex
     result — kyosu::acos(2.0) is complex — unless kyosu::real_only is passed, which falls back to the
     matching EVE function and its NaN.

   ### Supported algebras
   Starting from IEEE `float` and `double`:
   + [**Complex numbers**](https://en.wikipedia.org/wiki/Complex_number).
   + [**Quaternions**](https://en.wikipedia.org/wiki/Quaternion).
   + [**Octonions**](https://en.wikipedia.org/wiki/Octonion).
   + [**General algebras**](https://en.wikipedia.org/wiki/Cayley%E2%80%93Dickson_construction).

   Dimensions mix freely in an operation: the result takes the largest one and the missing components are
   zero. Adding a complex to a quaternion is a quaternion, and nothing branches to decide it.

   ### What is in the box
   + **The functions**, extended to hyper-complex arguments: Bessel functions, Legendre polynomials,
     elliptic integrals, and the usual transcendentals.
   + **The constructors**, for the parametrizations one actually reaches for — kyosu::from_euler,
     kyosu::from_spherical, kyosu::from_cylindrical, and axis-angle.
   + **The operators** `+`, `-`, `*`, `/`, plus left-division kyosu::ldiv, which a non-commutative algebra
     needs, and kyosu::muli and kyosu::mulmi for multiplication by \f$\pm i\f$.
   + **The constants** kyosu::i, kyosu::mi, kyosu::j, kyosu::k, and complex infinity.

   ## Hello World

   The same function over three algebras of growing dimension, mixed freely, then vectorized —
   without the maths changing a line.

   @godbolt{doc/hello.cpp}

   ## Licence

   This library is licensed under the [Boost Software License](https://opensource.org/licenses/BSL):

   ```text
   Copyright : KYOSU Project Contributors

   Boost Software License - Version 1.0 - August 17th, 2003

   Permission is hereby granted, free of charge, to any person or organization
   obtaining a copy of the software and accompanying documentation covered by
   this license (the "Software") to use, reproduce, display, distribute,
   execute, and transmit the Software, and to prepare derivative works of the
   Software, and to permit third-parties to whom the Software is furnished to
   do so, all subject to the following:

   The copyright notices in the Software and this entire statement, including
   the above license grant, this restriction and the following disclaimer,
   must be included in all copies of the Software, in whole or in part, and
   all derivative works of the Software, unless such copies or derivative
   works are solely in the form of machine-executable object code generated by
   a source language processor.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
   SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
   FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
   ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
   DEALINGS IN THE SOFTWARE.
   ```

**/