#error This file is for documentation only - DO NOT INCLUDE
//! @page tutorial-beyond Octonions and beyond
//!
//! Nothing in the construction stops at four dimensions. A pair of quaternions gives an octonion,
//! a pair of octonions a sedenion, and so on without end. **KYOSU** implements the whole tower, so
//! this page is about what changes as you climb it — and about the two places where habits
//! acquired on real numbers will mislead you.
//!
//! The mathematics is set out properly in @ref math_background. Here we only look at the code.
//!
//! # Naming any dimension
//!
//! Past the octonions the basis elements stop having traditional names and are simply indexed. The
//! type is named by its dimension:
//!
//! @godbolt{doc/tut_beyond_types.cpp}
//!
//! Every function of the library still applies, and still under the same name.
//!
//! # First trap: parentheses are load-bearing
//!
//! From dimension 8 on, \f$(ab)c\f$ and \f$a(bc)\f$ are different numbers. This is not a rounding
//! difference — the sign of a whole component flips:
//!
//! @godbolt{doc/tut_beyond_associativity.cpp}
//!
//! kyosu::associator computes \f$(ab)c - a(bc)\f$ directly, so the defect can be measured. On
//! quaternions and below it is zero; on octonions it is not. **KYOSU** never re-associates an
//! expression, so what you write is what is evaluated — which also means that a refactoring which
//! looks harmless can change the answer.
//!
//! # Second trap: from dimension 16, division fails
//!
//! Octonions still form a division algebra: every non-zero element has an inverse. Sedenions do
//! not. There exist non-zero values whose product is zero, and neither of them can be inverted:
//!
//! @godbolt{doc/tut_beyond_zero_divisors.cpp}
//!
//! Two perfectly finite operands, each of norm \f$\sqrt2\f$, with a product of exactly zero.
//!
//! Note what the trap is *not*. Nothing overflows, no NaN appears, and no exception is raised: the
//! answer is a finite, ordinary-looking zero. The multiplication has simply destroyed its operands,
//! and dividing back by \f$b\f$ returns zero rather than \f$a\f$. Above dimension 8 an algebraic
//! identity you would never think to question — that \f$ab\f$ determines \f$a\f$ once \f$b\f$ is
//! known — no longer holds, and nothing in the output will tell you.
//!
//! # What still works everywhere
//!
//! It would be reasonable to conclude that high dimensions are unusable. They are not, because the
//! property the elementary functions actually need survives at every level: the subalgebra
//! generated by a *single* element is always associative. So powers, exponentials, logarithms and
//! everything built on them remain well defined however far you go.
//!
//! @godbolt{doc/tut_beyond_functions.cpp}
//!
//! # Where to go from here
//!
//! The reference documentation lists every function by category, and @ref math_background gives
//! the construction, the theorems behind the losses above, and the scheme by which a real function
//! is extended to all of these algebras at once.
//!
//! <div class="section_buttons">
//!
//! | Previous                          |                                     Next |
//! |:----------------------------------|-----------------------------------------:|
//! | [Options](@ref tutorial-options)  | [Mathematical Background](@ref math_background) |
//!
//! </div>
